# Generated by Django 4.2.1 on 2024-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_utilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Installation', 'Installation'), ('Maintenance', 'Maintenance'), ('Repair', 'Repair')], default='Installation', max_length=100),
        ),
    ]
